baseurl = "http://mpas.github.io"
languageCode = "en-us"
title = "CodeVerse"
theme = "flyweight"
paginate = 10

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
mainSections = ["post"]

[Permalinks]
    post = "post/:year/:month/:day/:filename/"

[Taxonomies]
    tag = "tags"

[Params]
    # language code for your website
    languagecode = "en-US"

    # name of the site author; used in header meta information
    author = "Marco Pas"

    # social links; used in footer, these must be full URLs!
    twitter = "https://twitter.com/marcopas"
    github = "https://github.com/mpas"
    stackoverflow = "http://stackoverflow.com/users/185432/marco"
    linkedin = "https://www.linkedin.com/in/marcopas"
    email =  "mailto:marco.pasopas@gmail.com"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Post List"
    url = "/post"
    weight = 2

[[menu.main]]
    name = "About Me"
    url = "/page/about/"
    weight = 3

[[menu.main]]
    name = "Resume"
    url = "/page/resume"
    weight = 4

[params.strings]
    # used date format
    date_format = "2006-01-02"
